x-common-variables:
  &default-common
  restart: always
  env_file: ./.env
  dns:
    - ${DNS:-8.8.8.8}
    - ${DNS:-223.5.5.5}

services:

################  redis ########################
  redis-server:
    << : *default-common
    container_name: redis
    build:
      context: ./
      dockerfile: ./build/redis/Dockerfile
      args:
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        CHANGE_SOURCE: ${CHANGE_SOURCE}
        REDIS_VERSION: ${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    environment:
      # TZ: ${TZ}
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=${TZ}
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${REDIS_LOG_DIR}:/var/log/redis/:rw
    entrypoint: ["redis-server", "/etc/redis.conf"]
    deploy:
     resources:
        limits:
           cpus: ${REDIS_LIMITS_CPU}
           memory: ${REDIS_LIMITS_MEMORY}
        reservations:
           memory: ${REDIS_RESERVATIONS_MEMORY}
    networks:
      - default
    sysctls:
      - net.core.somaxconn=1024

################  MySQL ########################

# 采用官方二进制安装包安装，根据需要选择安装指定版本的mysql;
# 可有效避免docker仓库通过apt直接安装,因网络问题key无法下载问题。
# 缺点：采用该方式，会导致images文件大小会偏大一点
  mysql-server:
    << : *default-common
    container_name: mysql
    security_opt: # docker安全验证
      - seccomp:unconfined
    build:
      context: ./
      dockerfile: ./build/mysql/Dockerfile
      args:
        - MYSQL_VER=${MYSQL_VERSION}
        - GOSU_VERSION=${GOSU_VERSION}
        - MYSQL_DATA_DIR=${MYSQL_DATA_DIR}
        - CHANGE_SOURCE=${CHANGE_SOURCE}
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect='SET NAMES utf8mb4;'
      - --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      # - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
      #- ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/docker.cnf:ro
      - ${MYSQL_CONF_FILE}:/etc/mysql/my.cnf:ro
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    networks:
      default:
        aliases:
          - mysql-server
    deploy:
     resources:
        limits:
           cpus: ${MYSQL_LIMITS_CPU}
           memory: ${MYSQL_LIMITS_MEMORY}
        reservations:
           memory: ${MYSQL_RESERVATIONS_MEMORY}
    platform: linux/x86_64

  mysql8-server:
    << : *default-common
    container_name: mysql8
    security_opt: # docker安全验证
      - seccomp:unconfined
    build:
      context: ./
      dockerfile: ./build/mysql/Dockerfile_gf
      args:
        - MYSQL_VER=${MYSQL_VERSION}
        - GOSU_VERSION=${GOSU_VERSION}
        - CHANGE_SOURCE=${CHANGE_SOURCE}
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect='SET NAMES utf8mb4;'
      - --innodb-flush-log-at-trx-commit=0
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      # - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
      #- ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/docker.cnf:ro
      - ${MYSQL_CONF_FILE}:/etc/mysql/my.cnf:ro
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    networks:
      default:
        aliases:
          - mysql8-server
    deploy:
     resources:
        limits:
           cpus: ${MYSQL_LIMITS_CPU}
           memory: ${MYSQL_LIMITS_MEMORY}
        reservations:
           memory: ${MYSQL_RESERVATIONS_MEMORY}
    platform: linux/x86_64

  db-data-mysql:
    << : *default-common
    container_name: db-data-mysql
    image: busybox
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw

################   mongo ########################
  mongo-server:
    << : *default-common
    container_name: mongo
    image: mongo:${MONGODB_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_HOST_PORT}:27017"
    volumes:
      - ${MONGO_DATA_DB_DIR}:/data/db:rw
    deploy:
      resources:
        limits:
           cpus: ${MONGO_LIMITS_CPU}
           memory: ${MONGO_LIMITS_MEMORY}
        reservations:
           memory: ${MONGO_RESERVATIONS_MEMORY}
    networks:
      - default
    command:
      --auth

################   postgres  ########################
  postgres-server:
    << : *default-common
    container_name: postgres
    build:
      context: ./
      dockerfile: ./build/postgres/Dockerfile
      args:
        PG_VERSION: ${PG_VERSION}
        CHANGE_SOURCE: ${CHANGE_SOURCE}
    ports:
      - "${PG_PORT}:5432"
    environment:
      # - PG_USER=${PG_USER}
      # - PG_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - ALPINE_REPOSITORIES=${ALPINE_REPOSITORIES}
    volumes:
      - ${POSTGRES_DATA_DB_DIR}:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    deploy:
      resources:
        limits:
           cpus: ${PG_LIMITS_CPU}
           memory: ${PG_LIMITS_MEMORY}
        reservations:
           memory: ${PG_RESERVATIONS_MEMORY}
    networks:
      - default
    restart: unless-stopped

  pgadmin-server:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - default
    restart: unless-stopped