version: '3.9'

x-common-variables:
  &default-common
  restart: always
  env_file: ./.env
  dns:
    - ${DNS:-223.5.5.5}
    - ${DNS:-8.8.8.8}

services:

################  php83 #############################
  php83_apache:
    << : *default-common
    container_name: php83_apache
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
      args:
        SOURCE_LIST: bullseye
        PHP_VERSION: ${PHP83_VERSION}
        CHANGE_SOURCE: ${CHANGE_SOURCE}
        PHP_EXTENSIONS: ${PHP_COMMON_EXTENSIONS}
        LIBWEBP_VERSION: ${LIBWEBP_VERSION}
        XDEBUG_EXT_VERSION: ${XDEBUG_EXT_VERSION}
        SWOOLE_EXT_VERSION: ${SWOOLE_EXT_VERSION}
        GRPC_EXT_VERSION: ${GRPC_EXT_VERSION}
        REDIS_EXT_VERSION: ${REDIS_EXT_VERSION}
        LIBRDKAFKA_VERSION: ${LIBRDKAFKA_VERSION}
        RDKAFKA_EXT_VERSION: ${RDKAFKA_EXT_VERSION}
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
        ZOOKEEPER_EXT_VERSION: ${ZOOKEEPER_EXT_VERSION}
        PROTOBUF_VERSION: ${PROTOBUF_VERSION}
        PROTOBUF_EXT_VERSION: ${PROTOBUF_EXT_VERSION}
        MONGODB_EXT_VERSION: ${MONGODB_EXT_VERSION}
        IMAGICK_EXT_VERSION: ${IMAGICK_EXT_VERSION}
        IMAGICK_VERSION: ${IMAGICK_VERSION}
        MEMCACHED_VERSION: ${MEMCACHED_VERSION}
        OPENSSL_VERSION: ${OPENSSL_VERSION}
        CURL_VERSION: ${CURL_VERSION}
        LIBSODIUM_VERSION: ${LIBSODIUM_VERSION}
        LIBICONV_VERSION: ${LIBICONV_VERSION}
        FREETYPE_VERSION: ${FREETYPE_VERSION}
        YAML_EXT_VERSION: ${YAML_EXT_VERSION}
    volumes:
      - ${GLOBAL_WEB_PATH}:/var/www/html/:rw
      - ${APACHE_LOG_DIR}:/etc/apache2/logs/apache/:rw
      - ${APACHE_VHOST_DIR}:/etc/apache2/sites-enabled/:rw
      - ${PHP81_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    cap_add:
      - SYS_PTRACE
    networks:
      - default

################  php82 #############################
  php82_apache:
    << : *default-common
    container_name: php82_apache
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
      args:
        SOURCE_LIST: bullseye
        PHP_VERSION: ${PHP82_VERSION}
        CHANGE_SOURCE: ${CHANGE_SOURCE}
        PHP_EXTENSIONS: ${PHP_COMMON_EXTENSIONS}
        LIBWEBP_VERSION: ${LIBWEBP_VERSION}
        XDEBUG_EXT_VERSION: ${XDEBUG_EXT_VERSION}
        SWOOLE_EXT_VERSION: ${SWOOLE_EXT_VERSION}
        GRPC_EXT_VERSION: ${GRPC_EXT_VERSION}
        REDIS_EXT_VERSION: ${REDIS_EXT_VERSION}
        LIBRDKAFKA_VERSION: ${LIBRDKAFKA_VERSION}
        RDKAFKA_EXT_VERSION: ${RDKAFKA_EXT_VERSION}
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
        ZOOKEEPER_EXT_VERSION: ${ZOOKEEPER_EXT_VERSION}
        PROTOBUF_VERSION: ${PROTOBUF_VERSION}
        PROTOBUF_EXT_VERSION: ${PROTOBUF_EXT_VERSION}
        MONGODB_EXT_VERSION: ${MONGODB_EXT_VERSION}
        IMAGICK_EXT_VERSION: ${IMAGICK_EXT_VERSION}
        IMAGICK_VERSION: ${IMAGICK_VERSION}
        MEMCACHED_VERSION: ${MEMCACHED_VERSION}
        OPENSSL_VERSION: ${OPENSSL_VERSION}
        CURL_VERSION: ${CURL_VERSION}
        LIBSODIUM_VERSION: ${LIBSODIUM_VERSION}
        LIBICONV_VERSION: ${LIBICONV_VERSION}
        FREETYPE_VERSION: ${FREETYPE_VERSION}
        YAML_EXT_VERSION: ${YAML_EXT_VERSION}
    volumes:
      - ${GLOBAL_WEB_PATH}:/var/www/html/:rw
      - ${APACHE_LOG_DIR}:/etc/apache2/logs/apache/:rw
      - ${APACHE_VHOST_DIR}:/etc/apache2/sites-enabled/:rw
      - ${PHP81_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    cap_add:
      - SYS_PTRACE
    networks:
      - default

################   php81 ###################################
  php81_apache:
    << : *default-common
    container_name: php81_apache
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
      args:
        SOURCE_LIST: bullseye
        PHP_VERSION: ${PHP81_VERSION}
        CHANGE_SOURCE: ${CHANGE_SOURCE}
        PHP_EXTENSIONS: ${PHP_COMMON_EXTENSIONS}
        # MORE_EXTENSION_INSTALLER: php81.sh
        LIBWEBP_VERSION: ${LIBWEBP_VERSION}
        XDEBUG_EXT_VERSION: ${XDEBUG_EXT_VERSION}
        SWOOLE_EXT_VERSION: ${SWOOLE_EXT_VERSION}
        GRPC_EXT_VERSION: ${GRPC_EXT_VERSION}
        REDIS_EXT_VERSION: ${REDIS_EXT_VERSION}
        LIBRDKAFKA_VERSION: ${LIBRDKAFKA_VERSION}
        RDKAFKA_EXT_VERSION: ${RDKAFKA_EXT_VERSION}
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
        ZOOKEEPER_EXT_VERSION: ${ZOOKEEPER_EXT_VERSION}
        PROTOBUF_VERSION: ${PROTOBUF_VERSION}
        PROTOBUF_EXT_VERSION: ${PROTOBUF_EXT_VERSION}
        MONGODB_EXT_VERSION: ${MONGODB_EXT_VERSION}
        IMAGICK_EXT_VERSION: ${IMAGICK_EXT_VERSION}
        IMAGICK_VERSION: ${IMAGICK_VERSION}
        MEMCACHED_VERSION: ${MEMCACHED_VERSION}
        OPENSSL_VERSION: ${OPENSSL_VERSION}
        CURL_VERSION: ${CURL_VERSION}
        LIBSODIUM_VERSION: ${LIBSODIUM_VERSION}
        LIBICONV_VERSION: ${LIBICONV_VERSION}
        FREETYPE_VERSION: ${FREETYPE_VERSION}
        YAML_EXT_VERSION: ${YAML_EXT_VERSION}
    volumes:
      - ${GLOBAL_WEB_PATH}:/var/www/html/:rw
      - ${APACHE_LOG_DIR}:/etc/apache2/logs/apache/:rw
      - ${APACHE_VHOST_DIR}:/etc/apache2/sites-enabled/:rw
      - ${PHP81_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    cap_add:
      - SYS_PTRACE
    networks:
      - default

################   php80 ############################
  php80_apache:
    << : *default-common
    container_name: php80_apache
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
      args:
        SOURCE_LIST: bullseye
        PHP_VERSION: ${PHP80_VERSION}
        CHANGE_SOURCE: ${CHANGE_SOURCE}
        PHP_EXTENSIONS: ${PHP_COMMON_EXTENSIONS}
        # MORE_EXTENSION_INSTALLER: php80.sh
        LIBWEBP_VERSION: ${LIBWEBP_VERSION}
        XDEBUG_EXT_VERSION: ${XDEBUG_EXT_VERSION}
        SWOOLE_EXT_VERSION: ${SWOOLE_EXT_VERSION}
        GRPC_EXT_VERSION: ${GRPC_EXT_VERSION}
        REDIS_EXT_VERSION: ${REDIS_EXT_VERSION}
        LIBRDKAFKA_VERSION: ${LIBRDKAFKA_VERSION}
        RDKAFKA_EXT_VERSION: ${RDKAFKA_EXT_VERSION}
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
        ZOOKEEPER_EXT_VERSION: ${ZOOKEEPER_EXT_VERSION}
        PROTOBUF_VERSION: ${PROTOBUF_VERSION}
        PROTOBUF_EXT_VERSION: ${PROTOBUF_EXT_VERSION}
        MONGODB_EXT_VERSION: ${MONGODB_EXT_VERSION}
        IMAGICK_EXT_VERSION: ${IMAGICK_EXT_VERSION}
        IMAGICK_VERSION: ${IMAGICK_VERSION}
        MEMCACHED_VERSION: ${MEMCACHED_VERSION}
        OPENSSL_VERSION: ${OPENSSL_VERSION}
        CURL_VERSION: ${CURL_VERSION}
        LIBSODIUM_VERSION: ${LIBSODIUM_VERSION}
        LIBICONV_VERSION: ${LIBICONV_VERSION}
        FREETYPE_VERSION: ${FREETYPE_VERSION}
        YAML_EXT_VERSION: ${YAML_EXT_VERSION}
    volumes:
      - ${GLOBAL_WEB_PATH}:/var/www/html/:rw
      - ${APACHE_LOG_DIR}:/etc/apache2/logs/apache/:rw
      - ${APACHE_VHOST_DIR}:/etc/apache2/sites-enabled/:rw
      - ${PHP80_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    cap_add:
      - SYS_PTRACE
    networks:
      - default

################   php74 ##############################
  php74_apache:
    << : *default-common
    container_name: php74_apache
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
      args:
        SOURCE_LIST: bullseye
        PHP_VERSION: ${PHP74_VERSION}
        CHANGE_SOURCE: ${CHANGE_SOURCE}
        PHP_EXTENSIONS: ${PHP_COMMON_EXTENSIONS}
        # MORE_EXTENSION_INSTALLER: php74.sh
        LIBWEBP_VERSION: ${LIBWEBP_VERSION}
        SWOOLE_EXT_VERSION: ${SWOOLE_EXT_VERSION}
        XDEBUG_EXT_VERSION: ${XDEBUG_EXT_VERSION}
        GRPC_EXT_VERSION: ${GRPC_EXT_VERSION}
        REDIS_EXT_VERSION: ${REDIS_EXT_VERSION}
        LIBRDKAFKA_VERSION: ${LIBRDKAFKA_VERSION}
        RDKAFKA_EXT_VERSION: ${RDKAFKA_EXT_VERSION}
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
        ZOOKEEPER_EXT_VERSION: ${ZOOKEEPER_EXT_VERSION}
        PROTOBUF_VERSION: ${PROTOBUF_VERSION}
        PROTOBUF_EXT_VERSION: ${PROTOBUF_EXT_VERSION}
        MONGODB_EXT_VERSION: ${MONGODB_EXT_VERSION}
        IMAGICK_EXT_VERSION: ${IMAGICK_EXT_VERSION}
        IMAGICK_VERSION: ${IMAGICK_VERSION}
        MEMCACHED_VERSION: ${MEMCACHED_VERSION}
        OPENSSL_VERSION: ${OPENSSL_VERSION}
        CURL_VERSION: ${CURL_VERSION}
        LIBSODIUM_VERSION: ${LIBSODIUM_VERSION}
        LIBICONV_VERSION: ${LIBICONV_VERSION}
        FREETYPE_VERSION: ${FREETYPE_VERSION}
        YAML_EXT_VERSION: ${YAML_EXT_VERSION}
    volumes:
      - ${GLOBAL_WEB_PATH}:/var/www/html/:rw
      - ${APACHE_LOG_DIR}:/etc/apache2/logs/apache/:rw
      - ${APACHE_VHOST_DIR}:/etc/apache2/sites-enabled/:rw
      - ${PHP74_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    cap_add:
      - SYS_PTRACE
    networks:
      - default

################   php72 ##############################
  php72_apache:
    << : *default-common
    container_name: php72_apache
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
      args:
        SOURCE_LIST: bullseye
        PHP_VERSION: ${PHP72_VERSION}
        CHANGE_SOURCE: ${CHANGE_SOURCE}
        PHP_EXTENSIONS: ${PHP_COMMON_EXTENSIONS}
        # MORE_EXTENSION_INSTALLER: php72.sh
        LIBWEBP_VERSION: ${LIBWEBP_VERSION}
        XDEBUG_EXT_VERSION: ${XDEBUG_EXT_VERSION}
        GRPC_EXT_VERSION: ${GRPC_EXT_VERSION}
        REDIS_EXT_VERSION: ${REDIS_EXT_VERSION}
        LIBRDKAFKA_VERSION: ${LIBRDKAFKA_VERSION}
        RDKAFKA_EXT_VERSION: ${RDKAFKA_EXT_VERSION}
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
        ZOOKEEPER_EXT_VERSION: ${ZOOKEEPER_EXT_VERSION}
        PROTOBUF_VERSION: ${PROTOBUF_VERSION}
        PROTOBUF_EXT_VERSION: ${PROTOBUF_EXT_VERSION}
        MONGODB_EXT_VERSION: ${MONGODB_EXT_VERSION}
        IMAGICK_EXT_VERSION: ${IMAGICK_EXT_VERSION}
        IMAGICK_VERSION: ${IMAGICK_VERSION}
        MEMCACHED_VERSION: ${MEMCACHED_VERSION}
        OPENSSL_VERSION: ${OPENSSL_VERSION}
        CURL_VERSION: ${CURL_VERSION}
        LIBSODIUM_VERSION: ${LIBSODIUM_VERSION}
        LIBICONV_VERSION: ${LIBICONV_VERSION}
        FREETYPE_VERSION: ${FREETYPE_VERSION}
        YAML_EXT_VERSION: ${YAML_EXT_VERSION}
    volumes:
      - ${GLOBAL_WEB_PATH}:/var/www/html/:rw
      - ${APACHE_LOG_DIR}:/etc/apache2/logs/apache/:rw
      - ${APACHE_VHOST_DIR}:/etc/apache2/sites-enabled/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    cap_add:
      - SYS_PTRACE
    networks:
      - default
