version: '3'

x-common-variables:
  &default-common
  restart: always
  env_file: ./.env
  dns:
    - ${DNS:-223.5.5.5}
    - ${DNS:-8.8.4.4}

services:

################   nginx #######################################
  nginx-server:
    << : *default-common
    container_name: nginx
    build:
      context: ./
      dockerfile: ./build/nginx/Dockerfile
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - NGINX_VERSION=${NGINX_VERSION}
        - OPENSSL_VERSION=${OPENSSL_VERSION}
        - HMNM_VERSION=${HEADERS_MORE_NGINX_MODULE_VERSION}
        - PCRE_VERSION=${PCRE_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    privileged: true
    volumes:
      - ${GLOBAL_WEB_PATH}:/var/www/html/:rw
      - ${NGINX_VHOST_DIR}:/etc/nginx/conf/vhost/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/conf/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=${TZ}
    # depends_on:
      # - php83_apache
      # - php82_apache
      # - php81_apache
      # - php80_apache
      # - php74_apache
      # - php72_apache
    networks:
      - default

  # 如果需要使用tengine,请先注释掉上面的nginx代码，在取消下面的注释即可。

  tengine-server:
    << : *default-common
    container_name: tengine
    build:
      context: ./
      dockerfile: ./build/tengine/Dockerfile
      args:
        - ALPINE_REPOSITORIES=${ALPINE_REPOSITORIES}
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - TENGINE_VERSION=${TENGINE_VERSION}
        - HMNM_VERSION=${HEADERS_MORE_NGINX_MODULE_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    privileged: true
    volumes:
      - ${GLOBAL_WEB_PATH}:/var/www/html/:rw
      - ${NGINX_VHOST_DIR}:/etc/nginx/conf.d/:rw
      - ${TENGINE_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=${TZ}
    restart: always
    # depends_on:
    #   # - php83_apache
      # - php82_apache
    #   # - php81_apache
    #   # - php80_apache
      # - php74_apache
    #   # - php72_apache
    networks:
      - default