# ==========================================
# Prometheus监控配置 - PHP Docker环境
# ==========================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'php-docker-cluster'
    environment: '${ENVIRONMENT:-development}'

# 规则文件配置
rule_files:
  - "rules/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 监控目标配置
scrape_configs:
  # Prometheus自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # PHP Apache监控
  - job_name: 'php-apache'
    static_configs:
      - targets: 
          - 'php84_apache:88'
          - 'php83_apache:88'
          - 'php82_apache:88'
          - 'php81_apache:88'
          - 'php80_apache:88'
          - 'php74_apache:88'
          - 'php72_apache:88'
    scrape_interval: 15s
    metrics_path: /php-status
    params:
      auto: ['']
    scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        regex: '([^:]+):(.*)'
        target_label: php_version
        replacement: '${1}'

  # Docker容器监控 (如果有cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # 节点监控 (如果有Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

# 远程写入配置 (可选)
# remote_write:
#   - url: "http://your-remote-storage/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500 